#!/bin/bash
set -euxo pipefail

apt-get update
add-apt-repository ppa:deadsnakes/ppa -y
apt install vim unzip -y
git clone https://github.com/vuldin/local-ai-files.git workspace

# ensure docker uses mirror
echo '{"registry-mirrors": ["https://mirror.gcr.io"]}' > /etc/docker/daemon.json
echo 'DOCKER_OPTS="${DOCKER_OPTS} --registry-mirror=https://mirror.gcr.io"' >> /etc/default/docker

# enable container GPU access
#curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
#  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
#    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
#    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
#apt update
#apt install nvidia-container-toolkit
#nvidia-ctk runtime configure --runtime=docker
#systemctl restart docker
sudo service docker restart

# preemptively pull container images
docker pull docker.redpanda.com/redpandadata/redpanda:v24.3.4
docker pull docker.redpanda.com/redpandadata/console:v2.8.2
docker pull qdrant/qdrant:v1.13.2
docker pull ollama/ollama:0.5.7
docker pull vuldin/local-rag-ui

# install rpk
curl -LO https://github.com/redpanda-data/redpanda/releases/download/v24.2.4/rpk-linux-amd64.zip
mkdir -p /root/.local/bin
unzip rpk-linux-amd64.zip -d /root/.local/bin/
cat <<EOF > /root/.bash_profile
export PATH="/root/.local/bin:$PATH"
EOF

# get temporary license
curl -sLO https://gist.githubusercontent.com/vuldin/ba9b9ca7c90617809db4dc3160bb301a/raw/b7c4954fecea1a22483186ea1803041faf6cc356/redpanda.license
mkdir /etc/redpanda
cp redpanda.license /etc/redpanda

