#!/bin/bash
set -euxo pipefail

cd workspace

# create rpk profile
source ~/.bash_profile
rpk profile create local
rpk profile set kafka_api.brokers=redpanda:19092,redpanda:29092,redpanda:39092
rpk profile set admin_api.addresses=redpanda:19644,redpanda:29644,redpanda:39644
rpk profile use local

# start containers
docker-compose up -d

# pull models doesn't work
docker exec -i ollama ollama pull llama3.2
docker exec -i ollama ollama pull nomic-embed-text

# create qdrant collection
curl -X PUT "http://localhost:6333/collections/court-cases" \
     -H "Content-Type: application/json" \
     -d '{
           "vectors": {
             "size": 768,
             "distance": "Cosine"
           }
         }'

# create rpcn config
echo RP_BOOTSTRAP_SERVER="redpanda:19092"  >> .rpenv

